#!/bin/bash
# Removes everything generated by ANTLR, the compiler, and program runs.
# Source files (*.g4, MyVisitor.*, main.cpp, Symbol*.h, ScopeTable.h) are never touched.
cd "$(dirname "$0")" || exit 1

rm -f \
    CSubsetLexer.* CSubsetParser.* CSubsetVisitor.* CSubsetBaseVisitor.* \
    CSubset.interp CSubset.tokens \
    Lexer.interp Lexer.tokens \
    compiler.out \
    log.txt error.txt lexLogFile.txt

echo "Clean done."
